# Generated by Django 3.0.7 on 2020-06-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediablog', '0005_auto_20200626_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediablog',
            name='angry',
        ),
        migrations.RemoveField(
            model_name='mediablog',
            name='hahaha',
        ),
        migrations.RemoveField(
            model_name='mediablog',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='mediablog',
            name='love',
        ),
        migrations.RemoveField(
            model_name='mediablog',
            name='sad',
        ),
    ]
